### ISSUE TITLE
Travis-CI build fails

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#102]
Could you please have a look why the Travis-CI job for building this repo fails?

https://travis-ci.org/Caleydo/caleydo.github.io

```
The command "diff <(sed 's/['"'"'"]//g' _data/repos.yml) <(sed 's/['"'"'"]//g' _data/repos-expected.yml) || ( echo 'Regenerate repos.yml' && exit 1 )" exited with 1.
```

**Comment by mccalluc** [comment]
Most recent run failed in the expected way (because the docu_nav list really does need to change), but at some point while fetching from github the earlier run just conked out.

My thinking right now is that this shouldn't be run with every checkin: It's a fair number of hits against github, any one of them might fail, and even if there is a real discrepancy, it doesn't indicate there is a problem with this particular commit.

I think the fix is to have this test run only as a travis cron job. (Which I only learned existed today.) Once a day? So we will get a notification if an update needs to be made, but it won't be treated as a problem with one particular branch.

**Comment by thinkh** [comment]
Thanks for the explaination and taking care. I think updating the list via cron job once a day is sufficient.

**Comment by mccalluc** [comment]
(One point I just want to make sure is clear: Nothing is updating the list automatically; This will just be giving us warnings if the list is not in the state it should be. There could well be a better approach.)

They've say they've enabled it:  Here's the email:
>
Hello Chuck,
>
Thanks so much for your email! I've just enabled Cron Jobs for your organization: Caleydo.
>
Details on how to use them are in: https://docs.travis-ci.com/user/cron-jobs/
>
It's a beta feature at the moment, so please let us how it goes and if there's anything you feel can be improved or anything you miss.
>
Happy building and have a great day!
>
Anja

Except I'm not seeing it in the UI?
>
Thanks... though I'm not seeing anything below the environment variables section on https://travis-ci.org/Caleydo/caleydo.github.io/settings ... Build pushes is on, and I don't think there's anything else I need to check? Maybe I should just try again later in the day? 

<img width="817" alt="screen shot 2016-09-07 at 9 21 38 am" src="https://cloud.githubusercontent.com/assets/730388/18313571/636241b4-74dd-11e6-8508-297f00d7c110.png">

**Comment by mccalluc** [comment]
Sounds like a misunderstanding on their end. I've turned it on, and hopefully in the next 24 hours we'll see a run. I'll leave this open until I see it run, just be sure.
>
Thanks for the email and apologies for the confusion.
>
Our .com and .org services run on separate systems, and crons was only added to the Caleydo .com (private repository) account. I've updated the .org account now too, so crons should start appearing for all the Caleydo open source .org repos too.
>
Please get back in touch if you need any more help, or have any other questions.

**Comment by mstreit** [comment]
According to Travis the build check has passed.
