### ISSUE TITLE
Data Structures Tutorial: Clarify and extend demo 6

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo.github.io#164]
- web_bundle version: 0.0.1
- browser version: Firefox 49.0.1
- OS: Windows 10
### Reproducer:

Open [Data Structures Tutorial](http://www.caleydo.org/documentation/tutorial/data_structures/) or directly [Demo 6](http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?6)
### Observed behavior:

It's not really clear what this demo does, e.g., `print('Evens: ' + evens);` just prints `Evens: (0:10:2)`, which is exactly the values of the var `evens`.
### Expected behavior:

I suggest to extend/change the demo with the following points:

[ ] Add multiple input fields (or a range slider) where the user can enter the range that is applied to the sample matrix of demo 5
[ ] It would be also nice to do it the other way round, if the user selects or brushes the heat map that we print the actual range and the selected elements.
[ ] Pre-define some options, even, odds, etc. (as already done), but in a way that it shows a result (heat map)

**Comment by mccalluc** [comment]
> It's not really clear what this demo does, e.g., print('Evens: ' + evens); just prints Evens: (0:10:2), which is exactly the values of the var evens.

but printing out the string value of the union and intersection methods is useful.

I'd actually prefer to keep these examples static if at all possible, so that it's immediately obvious (to a human or a test runner) that the behavior is what we claim it is.

That said, I think this section is not well motivated, and it might be better done with method-by-method generated documentation, plus unit tests (https://github.com/phovea/phovea_core/issues/34), ... perhaps after that, just delete that section of the tutorial?

(Going to close this (because this belongs to phovea not caleydo), but feel free to file a new one there if needed.)
