### ISSUE TITLE
data.caleydo.org plans?

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#98]
There are several issues here, but I don't have a sense of direction and didn't want to litter this with bad bug reports.
- [ ] 1) If we have versioned releases of the bundles, then the API documentation should also probably be versioned? Could it be created as part of the build process? 
- [ ] 2) It's also not clear to me what's being documented here: Is this everything in the web bundle, or is it something else?
- [ ] 3) Clicking on any of the "Defined in" links just takes me to a blank page, and not to the given href: I think there's something weird going on here with an iframe, but I'm not sure how much is under our control, and how much is a product of the documentation generator.
- [ ] 4) Links on the right take me out of data.caleydo.org and over to caleydo.gehlenborg.com

**Comment by mstreit** [comment]
I assume that you refer to the API documentation that is hosted at http://data.caleydo.org/builds/lib/docs/.

re 1) Yes, versioning the documentation makes sense. The API documentation is already generated by the build server. See for example the last caleydo_lib.zip build: http://dev.caleydo.org/jenkins/job/caleydo_web_daily/. According to the configuration of the Jenkins job, the documentation is already updated automatically with every build over FTP (see http://dev.caleydo.org/jenkins/job/caleydo_web_daily/configure). I guess all we need to do is to create a new subfolder for every version by modifying the Jenkins job.

re 2) Yes, I think it contains the documentation of all repos that are referenced in the bundle lib repo (https://github.com/Caleydo/bundle_lib/blob/master/package.json).

re 3 and 4) I also don't know how to fix this.

**Comment by thinkh** [comment]
re 1) Yes, I fully aggree with @mccalluc suggestion. We should do that. However, I don't understand why the docs are available under http://data.caleydo.org/? Wouldn't it be better under http://docs.caleydo.org or http://api.caleydo.org, etc?

re 2) I haven't worked or read that API documentation so far. But we should check the "usefulness" of that API documentation and improve the comments in the source code. 

re 3 + 4) The problem occurs because the URL is cloaked using an iframe. You can see that in the source code view-source:http://data.caleydo.org/builds/lib/docs/. So @mccalluc assumption with the iframe is correct and it also answers the last question why it's linked to http://caleydo.gehlenborg.com/builds/lib/docs. By the way, if you open http://caleydo.gehlenborg.com/builds/lib/docs in a separate window/tab everything works fine.
@mstreit and @ngehlenborg Can you disable the URL cloaking or really link the domain to the webspace?

**Comment by mstreit** [comment]
re 1) The reason why we use data.caleydo.org is because the generated documentation is currently hosted at gehlenborg.org and we wanted to mask that.

**Comment by thinkh** [comment]
re 1) Can we host the documentation for each release on AWS S3, too? Would make it easier, I guess.

**Comment by mstreit** [comment]
re 1) Yes, we just need to update the Jenkins job.

**Comment by mstreit** [comment]
OK, let's host it on S3 as well.

**Comment by thinkh** [comment]
It's a bit tedious to upload all files manually. I had a look for an AWS S3 sync program, but they require an AWS access key, which @ngehlenborg will provide. Later we can automate that by using the Jenkins job.

**Comment by mstreit** [comment]
@ngehlenborg Did you already create the account that Jenkins can use for deploying the files to the S3 bucket?

**Comment by thinkh** [comment]
@mstreit Yes, he did that and send me the credentials. But I haven't tried them yet.

**Comment by mccalluc** [comment]
I think this is handled by https://github.com/phovea/phovea_bundle_lib/issues/8 and https://github.com/phovea/phovea_bundle_lib/issues/6
